<?php

namespace BasicDashboard\Web\Blogs\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Blogs\Services\BlogService;
use BasicDashboard\Web\Blogs\Validation\StoreBlogRequest;
use BasicDashboard\Web\Blogs\Validation\UpdateBlogRequest;
use BasicDashboard\Web\Blogs\Validation\DeleteBlogRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A BlogController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class BlogController extends BaseController
{
    public function __construct(
        private BlogService $blogService
    ) {
    }

    public function index(Request $request): View
    {
        return $this->blogService->index($request->all());
    }

    public function create(): View
    {
        return $this->blogService->create();
    }

    public function store(StoreBlogRequest $request): RedirectResponse
    {
        return $this->blogService->store($request->validated());
    }

    public function edit(string $id): View | RedirectResponse
    {
        return $this->blogService->edit($id);
    }

    public function show(string $id): View | RedirectResponse
    {
        return $this->blogService->show($id);
    }

    public function update(UpdateBlogRequest $request, string $id): RedirectResponse
    {
        return $this->blogService->update($request->validated(), $id);
    }

    public function destroy(DeleteBlogRequest $request): RedirectResponse
    {
        return $this->blogService->destroy($request->validated());
    }

}
