<?php
namespace BasicDashboard\Foundations\Domain\Blogs\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\Blogs\Blog;


/**
 *
 * A BlogRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface BlogRepositoryInterface extends BaseRepositoryInterface
{
    public function filterBlog(array $params): Builder | Blog;
    public function getBlogList($params): LengthAwarePaginator;
}