<?php

namespace BasicDashboard\Spa\Categories\Services;

use BasicDashboard\Foundations\Domain\Categories\Repositories\CategoryRepositoryInterface;
use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\Categories\Resources\CategoryResource;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A CategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryService extends BaseSpaController
{

    public function __construct(
        private CategoryRepositoryInterface $categoryRepositoryInterface,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): JsonResponse
    {
        $data = $this->categoryRepositoryInterface->getCategoryListForSpa();
        $data = CategoryResource::collection($data)->response()->getData(true);
        return $this->sendResponse("Index success", $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): JsonResponse
    {
        $data = $this->categoryRepositoryInterface->edit($id);
        $data= new CategoryResource($data);
        $data= $data->response()->getData(true)['data'];
        return $this->sendResponse('Show success',$data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
